/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CpuInfo: typeof import('./src/components/HardwareInformation/CpuInfo.vue')['default']
    DiskInfo: typeof import('./src/components/HardwareInformation/DiskInfo.vue')['default']
    GpuInfo: typeof import('./src/components/HardwareInformation/GpuInfo.vue')['default']
    HardwareInformation: typeof import('./src/components/HardwareInformation/index.vue')['default']
    LinkItem: typeof import('./src/components/LinkList/components/LinkItem.vue')['default']
    LinkList: typeof import('./src/components/LinkList/index.vue')['default']
    MemoryInfo: typeof import('./src/components/HardwareInformation/MemoryInfo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NetworkInfo: typeof import('./src/components/HardwareInformation/NetworkInfo.vue')['default']
    NH2: typeof import('naive-ui')['NH2']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPerformantEllipsis: typeof import('naive-ui')['NPerformantEllipsis']
    NPopover: typeof import('naive-ui')['NPopover']
    NProgress: typeof import('naive-ui')['NProgress']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    PopoverButton: typeof import('./src/components/PopoverButton/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusDot: typeof import('./src/components/LinkList/components/StatusDot.vue')['default']
  }
}
